name: Android UI SDK CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - support/SDK-V3
      - feature/**
      - bugfix/**
      - dependabot/**

jobs:
  build:
    # Compile the project using the predefined JDK versions in the strategy section
    runs-on: ubuntu-latest
    name: Build - JDK ${{ matrix.java-version }}

    strategy:
      fail-fast: false
      matrix:
        java-version: [ 17 ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build CORE SDK ${{ matrix.java-version }}
        run: ./gradlew --scan clean lint testDebugUnitTest jacocoTestCoverageVerification